export const GET_USERS_REQUESTED = "GET_USERS_REQUESTED";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_USERS_FAILED = "GET_USERS_FAILED";


//delete
export const GET_USERS_DELETE = "GET_USERS_DELETE";
export const GET_USERS_DELETE_SUCCESS = "GET_USERS_DELETE_SUCCESS";
export const GET_USERS_DELETE_FAILED = "GET_USERS_DELETE_FAILED";
